export const servicesBodyHtml = `
<main>
  <nav aria-label="Breadcrumb"><a href="/">Home</a> &rsaquo; <span>Services</span></nav>
  <h1>Digital Marketing Services Birmingham</h1>
  <p>Cornerstone Media is a full-service digital marketing agency in Birmingham delivering expert <a href="/seo-birmingham">SEO</a>, <a href="/ppc-birmingham">PPC advertising</a>, <a href="/social-media-marketing-birmingham">social media marketing</a>, and <a href="/website-design-birmingham">website design</a> services that generate measurable leads, sales, and revenue for businesses across the West Midlands.</p>

  <h2>Digital Marketing Agency Birmingham</h2>
  <p>Birmingham is one of the most competitive business markets in the United Kingdom. With over 45,000 registered businesses, standing out online demands a strategic, data-driven approach that aligns every channel with your commercial objectives.</p>
  <p>What sets us apart is our integrated approach — rather than treating SEO, PPC, social media, and web design as separate services, we build unified strategies where every channel reinforces the others for faster growth and stronger ROI.</p>
  <p>Cornerstone Media was founded to give Birmingham businesses access to the same calibre of digital marketing expertise previously only available to companies with London-sized budgets. We bring enterprise-level strategy, tools, and execution to businesses of every size — from independent retailers in the Jewellery Quarter to professional services firms in Colmore Row and manufacturers across the wider West Midlands.</p>
  <p>Whether you need to generate more leads, increase online sales, build brand awareness, or establish authority in your industry, our team of specialists will create and execute a bespoke digital marketing plan designed around your specific goals, budget, and timeline.</p>

  <h2>SEO Services Birmingham</h2>
  <p>Search engine optimisation is the foundation of any successful online marketing strategy. Our SEO Birmingham services help your business rank higher in Google for the keywords that matter most — driving consistent, high-quality organic traffic without ongoing advertising costs. <a href="/seo-birmingham">Learn more about SEO Birmingham</a></p>
  <p>Our SEO process covers every aspect of search visibility. We begin with comprehensive keyword research to identify the search terms your ideal customers use when looking for products or services like yours in Birmingham.</p>
  <p>Technical SEO ensures your website meets Google's crawling, indexing, and rendering requirements. We audit site speed, mobile responsiveness, URL structure, schema markup, internal linking, and Core Web Vitals.</p>
  <p>On-page SEO involves optimising titles, meta descriptions, headings, content, images, and internal links. We also implement local SEO strategies including Google Business Profile optimisation and geo-targeted content.</p>

  <h2>PPC Services Birmingham</h2>
  <p>Pay-per-click advertising delivers immediate visibility and leads for your Birmingham business. Our PPC specialists manage high-performance Google Ads campaigns that put your business in front of customers at the exact moment they search. <a href="/ppc-birmingham">Learn more about PPC Birmingham</a></p>
  <p>We build paid search campaigns around commercial intent keywords, ensuring your budget is spent on clicks most likely to convert. Every campaign includes audience targeting, ad copy testing, and landing page optimisation.</p>
  <p>Our PPC management includes remarketing campaigns that re-engage visitors who have already shown interest. Combined with conversion tracking, we measure every lead and sale generated by your ads.</p>
  <p>Whether launching a new product or building a consistent lead generation engine, PPC provides speed and precision that organic channels cannot match. Our clients typically see their first leads within the first week.</p>

  <h2>Social Media Marketing Birmingham</h2>
  <p>Social media is where your Birmingham audience spends their time. Our social media marketing services help you build a loyal following, generate leads, and increase brand awareness across the platforms that matter most. <a href="/social-media-marketing-birmingham">Learn more about Social Media Marketing Birmingham</a></p>
  <p>We develop bespoke content creation strategies combining eye-catching visuals, compelling copy, and strategic posting schedules to maximise reach and engagement across Facebook, Instagram, LinkedIn, and TikTok.</p>
  <p>Beyond organic management, we run targeted paid social advertising campaigns that put your business in front of precisely defined audiences based on demographics, interests, behaviours, and location.</p>
  <p>Our engagement strategies go beyond posting — we actively manage community interactions, respond to comments, and build genuine relationships that translate into repeat business and referrals across Birmingham.</p>

  <h2>Content Writing</h2>
  <p>SEO-optimised blog posts, website copy, and content strategy that drives organic traffic and conversions. <a href="/content-writing">Learn more about Content Writing</a></p>
  <ul>
    <li>Blog Writing</li>
    <li>Web Copy</li>
    <li>SEO Content</li>
    <li>Brand Storytelling</li>
  </ul>

  <h2>Website Design Birmingham</h2>
  <p>Your website is the hub of your entire digital presence. Every SEO ranking, PPC click, and social media interaction drives visitors to your site — its design and speed directly determine how many become paying customers. <a href="/website-design-birmingham">Learn more about Website Design Birmingham</a></p>
  <p>We specialise in responsive websites that deliver a flawless experience across desktops, tablets, and smartphones. With over 60% of web traffic from mobile, a mobile-first approach is essential.</p>
  <p>Every website is built with conversion-focused design principles — strategic CTAs, streamlined user journeys, and zero friction points that prevent visitors from taking the next step.</p>
  <p>Performance matters. Google uses page speed as a ranking factor. We build fast-loading websites using modern technologies achieving excellent Core Web Vitals scores for both rankings and user experience.</p>

  <h2>Website Maintenance</h2>
  <p>Keep your site secure, fast, and up-to-date with ongoing maintenance, monitoring, and performance optimisation. <a href="/website-maintenance">Learn more about Website Maintenance</a></p>
  <ul>
    <li>Security Updates</li>
    <li>Performance Monitoring</li>
    <li>Backups</li>
    <li>Uptime Guarantee</li>
  </ul>

  <h2>Our Full Range of Digital Marketing Services</h2>
  <p>Each service is delivered by experienced specialists focused on generating measurable business growth.</p>
  <h3><a href="/ppc-birmingham">PPC Advertising</a></h3>
  <p>Drive high-intent traffic with expertly managed Google Ads campaigns that maximise every pound of your budget.</p>
  <h3><a href="/seo-birmingham">SEO Services</a></h3>
  <p>Climb Google rankings with technical SEO, content strategy, and authoritative link building that compounds over time.</p>
  <h3><a href="/social-media-marketing-birmingham">Social Media Marketing</a></h3>
  <p>Build brand awareness and drive engagement through strategic social media campaigns tailored to the Birmingham market.</p>
  <h3><a href="/content-writing">Content Writing</a></h3>
  <p>SEO-optimised blog posts, website copy, and content strategy that drives organic traffic and conversions.</p>
  <h3><a href="/website-design-birmingham">Website Design</a></h3>
  <p>Conversion-focused website design — beautifully crafted, blazing fast, and optimised for every device.</p>
  <h3><a href="/website-maintenance">Website Maintenance</a></h3>
  <p>Keep your site secure, fast, and up-to-date with ongoing maintenance, monitoring, and performance optimisation.</p>

  <h2>Our Digital Marketing Process</h2>
  <p>A proven four-stage process that takes your Birmingham business from audit to sustained growth.</p>
  <h3>01. Discovery &amp; Audit</h3>
  <p>Comprehensive audit of your digital presence, website, search visibility, competitors, and Birmingham market opportunities.</p>
  <h3>02. Strategy Development</h3>
  <p>Tailored digital marketing strategy with clear objectives, timelines, and measurable KPIs aligned to your goals.</p>
  <h3>03. Execution</h3>
  <p>Specialist teams execute across all channels — from technical SEO and Google Ads to content creation and social media.</p>
  <h3>04. Measure &amp; Optimise</h3>
  <p>Continuous monitoring, analysis, and optimisation with monthly reports on traffic, leads, conversions, and revenue.</p>

  <h2>Why Choose Cornerstone Media</h2>
  <p>Your growth partner — a Birmingham-based team delivering measurable results that impact your bottom line.</p>
  <h3>Results-Driven</h3>
  <p>Every campaign is built around measurable KPIs — conversions, revenue, and ROI, not vanity metrics.</p>
  <h3>Birmingham Experts</h3>
  <p>We understand the local business landscape, competition, and customer behaviour unique to the West Midlands.</p>
  <h3>Transparent Reporting</h3>
  <p>Monthly reports with clear data on traffic, leads, and revenue so you always know how your investment performs.</p>
  <h3>Integrated Strategy</h3>
  <p>Our services work together — SEO supports PPC, content fuels social, and design underpins everything.</p>

  <h2>Frequently Asked Questions</h2>
  <h3>What digital marketing services do Birmingham businesses need?</h3>
  <p>Most Birmingham businesses benefit from a combination of SEO, PPC advertising, social media marketing, and a professionally designed website. The right mix depends on your industry, budget, and growth goals. A local retailer might prioritise Google Ads and local SEO, while a B2B company may focus on LinkedIn marketing and content strategy. We offer a free consultation to help you identify the highest-impact services for your specific situation.</p>
  <h3>How long does SEO take to work?</h3>
  <p>SEO is a long-term investment. Most Birmingham businesses start seeing measurable improvements in organic traffic within 3 to 6 months, with significant ranking gains typically appearing between 6 and 12 months. The timeline depends on your starting position, industry competitiveness, and the quality of your website. Our SEO Birmingham team provides monthly progress reports so you can track keyword movements, traffic growth, and lead generation from day one.</p>
  <h3>Is PPC better than SEO?</h3>
  <p>PPC and SEO serve different but complementary purposes. PPC delivers immediate visibility and leads — you can start generating enquiries within days of launching Google Ads campaigns. SEO builds sustainable, long-term organic traffic that doesn't require ongoing ad spend. The most effective digital marketing strategies combine both: PPC for instant results and SEO for compounding growth. Our Birmingham clients who invest in both channels consistently see the strongest overall ROI.</p>
  <h3>How much does digital marketing cost in Birmingham?</h3>
  <p>Digital marketing costs vary based on the services you need, the competitiveness of your industry, and your growth ambitions. PPC budgets can start from a few hundred pounds per month, while comprehensive SEO campaigns typically require a larger ongoing investment. We provide transparent pricing with no hidden fees and tailor packages to suit businesses of all sizes in Birmingham. Contact us for a free quote based on your specific requirements.</p>
  <h3>Do you work with small businesses in Birmingham?</h3>
  <p>Absolutely. We work with businesses of all sizes across Birmingham and the West Midlands — from sole traders and startups to established companies with multiple locations. Many of our most successful partnerships started with a single service and expanded as the business grew. We tailor our pricing and approach to match your scale, ensuring you get maximum value regardless of budget size.</p>
  <h3>What makes Cornerstone Media different from other Birmingham marketing agencies?</h3>
  <p>We combine deep technical expertise with creative execution and genuine local market knowledge. Unlike larger agencies where you become just another account, we provide dedicated attention and personalised strategy. We are transparent about pricing, honest about timelines, and focused entirely on delivering measurable business growth for Birmingham companies.</p>
  <h3>Can I combine multiple digital marketing services?</h3>
  <p>Yes, and we strongly recommend it. An integrated approach delivers far better results than treating each channel in isolation. For example, combining SEO with PPC means the keyword data from your paid campaigns directly improves your organic strategy. Social media builds brand awareness that lifts click-through rates across search. And a well-designed website ensures all traffic converts into genuine leads and sales.</p>

  <p>Ready to grow your Birmingham business? <a href="/contact">Get in touch</a> or call <a href="tel:07846798534">07846 798 534</a> to book your free strategy consultation.</p>
</main>
`;
