import { MapPin } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ServicePageLayout from "@/components/ServicePageLayout";
import SEOHead from "@/components/SEOHead";

const DigitalMarketingSuttonColdfield = () => (
  <div className="min-h-screen bg-background">
    <SEOHead title="Digital Marketing Sutton Coldfield | Marketing Agency | Cornerstone Media" description="Digital marketing services for Sutton Coldfield businesses. SEO, PPC, social media marketing, and web design from Birmingham's trusted agency Cornerstone Media." canonical="https://cornerstone-media.co.uk/digital-marketing-sutton-coldfield" />
    <Navbar />
    <main>
      <ServicePageLayout icon={MapPin} title="Digital Marketing Sutton Coldfield" subtitle="Marketing Services for Sutton Coldfield" description="Cornerstone Media delivers expert digital marketing services to businesses in Sutton Coldfield. Located in neighbouring Birmingham, we provide Sutton Coldfield businesses with the same calibre of SEO, PPC, social media, and website design services that drive growth for companies across the West Midlands."
        benefits={["Local SEO targeting Sutton Coldfield search terms to capture customers searching for services in the Royal Town and surrounding villages","Google Ads campaigns geo-targeted to Sutton Coldfield, Four Oaks, Mere Green, and Walmley postcodes for maximum local relevance","Social media strategies connecting your brand with Sutton Coldfield's engaged community across Facebook, Instagram, and LinkedIn","Professional website design reflecting the quality and heritage that Sutton Coldfield businesses are known for","Content marketing establishing your authority within Sutton Coldfield's thriving local economy","Multi-channel marketing strategies tailored to the demographics and consumer behaviour of Sutton Coldfield residents"]}
        detailedSections={[{heading:"Why Sutton Coldfield Businesses Need Digital Marketing",paragraphs:["Sutton Coldfield — the Royal Town — is one of the most affluent areas in the West Midlands with a strong local economy driven by independent businesses, professional services firms, and a thriving high street. The town's residents are digitally engaged and increasingly use online search to find local products and services, making digital marketing essential for businesses wanting to capture this valuable market.","The local business landscape in Sutton Coldfield is competitive. From the independent shops along the Parade and in Mere Green to the professional services clustered around the town centre, businesses compete for the attention of discerning local consumers who expect quality and professionalism. A strong online presence helps differentiate your business and build the trust needed to win new customers.","Cornerstone Media understands the Sutton Coldfield market. We know that local search dominates how residents find businesses, that reputation and reviews carry significant weight in this community, and that the town's unique character requires marketing that feels authentic rather than generic. Our strategies are built around these local insights."]},{heading:"Digital Marketing Opportunities in Sutton Coldfield",paragraphs:["Sutton Coldfield's affluent demographics present significant opportunities for businesses that invest in digital marketing. Higher disposable incomes mean larger average transaction values, while the community-minded nature of the town means that businesses with strong local visibility build loyal customer bases that generate consistent referrals.","Local SEO is particularly impactful in Sutton Coldfield. When residents search for services like 'solicitor Sutton Coldfield' or 'restaurant near Four Oaks', they expect to find established local businesses. Ranking in Google's local pack for these searches puts your business directly in front of high-intent customers ready to enquire or visit.","We also see strong results from targeted social media marketing in Sutton Coldfield. The town's active community groups and engaged social media users create opportunities for businesses to build brand awareness and generate word-of-mouth through strategic content and paid social campaigns."]}]}
        topics={[{title:"Sutton Coldfield SEO",description:"Local search optimisation targeting Sutton Coldfield keywords, Google Business Profile management, and local content that captures nearby search demand."},{title:"PPC for Sutton Coldfield",description:"Geo-targeted Google Ads reaching customers in Sutton Coldfield, Four Oaks, Mere Green, Boldmere, and Walmley with high-intent search campaigns."},{title:"Social Media",description:"Community-focused social media marketing connecting your brand with Sutton Coldfield's engaged residents through Facebook, Instagram, and local groups."},{title:"Web Design",description:"Professional website design for Sutton Coldfield businesses with local SEO built in and conversion-focused layouts."}]}
        processSteps={[{title:"Local Discovery",description:"We analyse your Sutton Coldfield market, competitors, and customer search patterns to identify the biggest growth opportunities."},{title:"Bespoke Strategy",description:"We build a marketing plan combining the optimal mix of channels to reach Sutton Coldfield customers effectively."},{title:"Implementation",description:"Our teams execute campaigns with Sutton Coldfield-specific targeting, messaging, and creative across all chosen channels."},{title:"Growth & Reporting",description:"We track results, report monthly, and refine strategies to deliver sustained business growth in the Sutton Coldfield market."}]}
        faqs={[{question:"Are you based near Sutton Coldfield?",answer:"Yes. Our Birmingham office is a short drive from Sutton Coldfield, and we regularly meet clients across the Royal Town. We understand the local market and community."},{question:"Can you help my Sutton Coldfield business rank in Google?",answer:"Absolutely. Our local SEO services target Sutton Coldfield-specific keywords and optimise your Google Business Profile to improve visibility in local search results and Google Maps."},{question:"What size businesses do you work with in Sutton Coldfield?",answer:"We work with businesses of all sizes — from sole traders and independent shops to larger companies with multiple employees. Our services scale to match your needs and budget."},{question:"Do you offer free consultations?",answer:"Yes. We offer a free initial consultation where we discuss your business goals and provide recommendations on the best digital marketing approach for your Sutton Coldfield business."}]}
        relatedServices={[{name:"SEO Birmingham",path:"/seo-birmingham",description:"Full SEO services for businesses across Birmingham and the wider West Midlands."},{name:"Local SEO Birmingham",path:"/local-seo-birmingham",description:"Specialist local SEO helping businesses dominate Google Maps and local search results."},{name:"Website Design Birmingham",path:"/website-design-birmingham",description:"Professional website design for businesses across Birmingham and surrounding areas."}]}
      />
    </main>
    <Footer />
  </div>
);
export default DigitalMarketingSuttonColdfield;
