import { MapPin } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ServicePageLayout from "@/components/ServicePageLayout";
import SEOHead from "@/components/SEOHead";

const DigitalMarketingSolihull = () => (
  <div className="min-h-screen bg-background">
    <SEOHead title="Digital Marketing Solihull | Cornerstone Media" description="SEO, PPC, social media & web design for Solihull businesses, from Cornerstone Media — Birmingham's trusted marketing agency." canonical="https://cornerstone-media.co.uk/digital-marketing-solihull" />
    <Navbar />
    <main>
      <ServicePageLayout icon={MapPin} title="Digital Marketing Solihull" subtitle="Marketing Services for Solihull Businesses" description="Cornerstone Media provides expert digital marketing services for businesses in Solihull and the surrounding area. As a Birmingham-based agency just minutes from Solihull, we combine deep local knowledge with proven digital marketing expertise to help Solihull businesses grow online through SEO, PPC advertising, social media marketing, and professional website design."
        benefits={["Local SEO strategies targeting Solihull-specific search terms and Google Maps visibility for businesses serving the borough","Google Ads campaigns geo-targeted to reach customers actively searching for services in Solihull, Shirley, Dorridge, and Knowle","Social media marketing connecting your brand with Solihull's affluent consumer base across Facebook, Instagram, and LinkedIn","Website design that reflects the quality expectations of Solihull's discerning business community and customer base","Content marketing positioning your Solihull business as a trusted local authority in your industry","Integrated multi-channel strategies that combine SEO, PPC, and social media for maximum impact in the Solihull market"]}
        detailedSections={[{heading:"Why Solihull Businesses Choose Cornerstone Media",paragraphs:["Solihull is one of the most prosperous boroughs in the West Midlands, home to a thriving business community ranging from independent retailers in Touchwood and Mell Square to corporate headquarters along the M42 corridor. The borough's strong economy and affluent demographics create significant opportunities for businesses that invest in effective digital marketing.","However, Solihull's competitive landscape means that standing out online requires more than a basic website and occasional social media posts. Businesses here compete not only with each other but with Birmingham city centre and national brands. A strategic, data-driven approach to digital marketing is essential for capturing the attention of Solihull's digitally savvy consumers.","As a marketing agency based in neighbouring Birmingham, Cornerstone Media understands the Solihull market intimately. We know the local business landscape, the consumer demographics, and the search behaviour patterns specific to the borough. This local expertise, combined with our full-service digital marketing capabilities, makes us the ideal partner for Solihull businesses looking to grow online."]},{heading:"Digital Marketing Challenges in Solihull",paragraphs:["Solihull businesses face unique digital marketing challenges. The borough sits between Birmingham and Coventry, meaning search competition comes from multiple directions. Local businesses must compete for visibility against larger Birmingham-based companies while also standing out from national chains operating in the area.","The residential nature of much of Solihull means that local search — particularly Google Maps and 'near me' queries — is critical for businesses serving the local community. Restaurants, retailers, professional services, and tradespeople all depend heavily on appearing in local search results when Solihull residents look for services nearby.","Our digital marketing strategies for Solihull businesses are designed to address these specific challenges. We combine local SEO to capture nearby search demand, targeted PPC advertising for immediate visibility, and content marketing that establishes your authority within the Solihull community."]}]}
        topics={[{title:"SEO for Solihull Businesses",description:"Keyword targeting for Solihull-specific search terms, Google Business Profile optimisation, local citation building, and geo-targeted content creation."},{title:"PPC Advertising in Solihull",description:"Google Ads campaigns targeting Solihull postcodes and surrounding areas with commercial-intent keywords and conversion-optimised landing pages."},{title:"Social Media Marketing",description:"Building your brand presence across Facebook, Instagram, and LinkedIn with content tailored to Solihull's audience demographics and interests."},{title:"Website Design",description:"Professional, conversion-focused websites designed for Solihull businesses with local SEO foundations and mobile-first responsive design."}]}
        processSteps={[{title:"Local Market Analysis",description:"We research your Solihull market, competitors, and customer search behaviour to build a data-driven strategy."},{title:"Strategy Development",description:"We create a tailored digital marketing plan combining the right mix of SEO, PPC, social, and web design for your goals."},{title:"Campaign Execution",description:"Our specialist teams implement campaigns across all chosen channels with Solihull-specific targeting and messaging."},{title:"Results & Growth",description:"We monitor performance, report monthly, and continuously optimise campaigns for sustained growth in the Solihull market."}]}
        faqs={[{question:"Do you work with businesses in Solihull?",answer:"Yes. We work with numerous businesses across Solihull including Shirley, Dorridge, Knowle, and the town centre. As a Birmingham-based agency, we are just minutes away and offer face-to-face meetings."},{question:"Can you target just Solihull with my marketing?",answer:"Absolutely. We can geo-target PPC campaigns, local SEO, and social media advertising specifically to Solihull and surrounding postcodes."},{question:"What types of Solihull businesses do you work with?",answer:"We work with all types — from independent retailers and restaurants to professional services firms, tradespeople, and B2B companies operating in and around Solihull."},{question:"How much does digital marketing cost for a Solihull business?",answer:"Costs depend on which services you need and the competitiveness of your market. We offer tailored packages to suit businesses of all sizes. Contact us for a free consultation."}]}
        relatedServices={[{name:"SEO Birmingham",path:"/seo-birmingham",description:"Comprehensive SEO services for businesses across Birmingham and the wider West Midlands region."},{name:"PPC Birmingham",path:"/ppc-birmingham",description:"Expert Google Ads management driving leads and sales for businesses across the West Midlands."},{name:"Website Design Birmingham",path:"/website-design-birmingham",description:"Professional website design for businesses in Birmingham, Solihull, and surrounding areas."}]}
      />
    </main>
    <Footer />
  </div>
);
export default DigitalMarketingSolihull;
