import { MapPin } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ServicePageLayout from "@/components/ServicePageLayout";
import SEOHead from "@/components/SEOHead";

const DigitalMarketingDudley = () => (
  <div className="min-h-screen bg-background">
    <SEOHead title="Digital Marketing Dudley | Marketing Agency Near Dudley | Cornerstone Media" description="Digital marketing services for Dudley businesses. SEO, PPC, social media, and website design from Cornerstone Media. Expert marketing for Black Country businesses." canonical="https://cornerstone-media.co.uk/digital-marketing-dudley" />
    <Navbar />
    <main>
      <ServicePageLayout icon={MapPin} title="Digital Marketing Dudley" subtitle="Marketing Services for Dudley Businesses" description="Cornerstone Media delivers results-driven digital marketing services to businesses in Dudley and across the Black Country. Our SEO, PPC, social media, and website design services help Dudley businesses increase their online visibility, generate qualified leads, and grow revenue through strategic, data-driven digital marketing."
        benefits={["Local SEO strategies targeting Dudley-specific keywords and Google Maps to capture customers searching in the borough","PPC campaigns geo-targeted to Dudley, Stourbridge, Halesowen, Brierley Hill, and surrounding DY postcodes","Social media marketing connecting Dudley businesses with their local community and building brand loyalty","Professional website design that showcases your Dudley business with credibility and drives visitor conversions","Content marketing with locally relevant articles and service pages targeting Black Country search demand","Integrated marketing strategies combining multiple channels for comprehensive coverage of the Dudley market"]}
        detailedSections={[{heading:"Digital Marketing for Dudley and the Black Country",paragraphs:["Dudley is one of the four metropolitan boroughs of the Black Country, with a proud industrial heritage and a diverse modern economy. The borough encompasses Dudley town centre, Stourbridge, Halesowen, Brierley Hill, and numerous villages, creating a substantial local market for businesses serving residential and commercial customers.","Digital marketing is transforming how Dudley businesses reach their customers. The shift to online search, social media, and e-commerce means that businesses without a strong digital presence are losing ground to competitors who invest in their online visibility. Whether you operate a shop on Dudley High Street, a trade business serving the borough, or a professional services firm, digital marketing is essential for growth.","Cornerstone Media works with businesses across the Black Country, bringing Birmingham-level digital marketing expertise to Dudley's business community. We understand the local market dynamics, the competitive landscape, and the specific search behaviours of Black Country consumers. Our strategies are designed to deliver maximum impact within realistic budgets."]},{heading:"Why Dudley Businesses Need a Local Marketing Partner",paragraphs:["Dudley's business community benefits from working with a marketing agency that understands the West Midlands. National agencies often overlook the nuances of marketing in the Black Country — the importance of local identity, the overlapping service areas between boroughs, and the price-conscious but quality-aware consumer base.","Our proximity to Dudley means we can meet face-to-face, understand your business first-hand, and provide the responsive, personal service that makes a real difference. We are invested in the success of West Midlands businesses and take pride in helping Dudley companies grow through effective digital marketing."]}]}
        topics={[{title:"Dudley SEO",description:"Local search optimisation for Dudley businesses including Google Business Profile management, keyword targeting, and local content strategy."},{title:"PPC for Dudley",description:"Targeted Google Ads campaigns reaching customers in Dudley, Stourbridge, Halesowen, and Brierley Hill with conversion-focused advertising."},{title:"Social Media",description:"Brand building and community engagement through Facebook, Instagram, and LinkedIn tailored to Dudley's local audience."},{title:"Website Design",description:"Professional, mobile-responsive websites for Dudley businesses with built-in SEO and clear calls-to-action."}]}
        processSteps={[{title:"Discovery",description:"We learn about your Dudley business, market, competitors, and goals through an initial consultation."},{title:"Strategy",description:"We develop a tailored digital marketing plan with channel recommendations optimised for the Dudley market."},{title:"Execution",description:"Our specialists implement and manage campaigns with local targeting across all chosen channels."},{title:"Results",description:"Monthly performance reporting with clear metrics showing the impact on your Dudley business growth."}]}
        faqs={[{question:"Do you work with Dudley businesses?",answer:"Yes. We serve businesses across Dudley borough including Stourbridge, Halesowen, Brierley Hill, and surrounding areas."},{question:"How far is your office from Dudley?",answer:"Our Birmingham office is approximately 20 minutes from Dudley by car, making face-to-face meetings easy and convenient."},{question:"Can you help with Google Maps visibility in Dudley?",answer:"Absolutely. Our local SEO services include Google Business Profile optimisation to improve your visibility in Google Maps and local search results for Dudley searches."},{question:"What results can I expect?",answer:"Results depend on your starting position, industry, and chosen services. We provide realistic projections and report transparently on progress each month."}]}
        relatedServices={[{name:"SEO Birmingham",path:"/seo-birmingham",description:"Comprehensive SEO for businesses across the West Midlands."},{name:"PPC Birmingham",path:"/ppc-birmingham",description:"Expert PPC management for Black Country and West Midlands businesses."},{name:"Social Media Marketing Birmingham",path:"/social-media-marketing-birmingham",description:"Strategic social media for West Midlands businesses."}]}
      />
    </main>
    <Footer />
  </div>
);
export default DigitalMarketingDudley;
