#!/usr/bin/env node
// Post-build sitemap generation.
// Copies public/sitemap.xml (already in dist after vite build) and appends one
// <url> entry per published blog post read from the blog_posts table, so new
// posts are included automatically without hand-editing the sitemap.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SITE_ORIGIN } from "./seo-routes.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");

async function loadEnv() {
  const env = { ...process.env };
  try {
    const raw = await fs.readFile(path.join(ROOT, ".env"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  } catch {
    /* no .env file — rely on process.env */
  }
  return env;
}

async function fetchPublishedPosts(env) {
  const url = env.VITE_SUPABASE_URL;
  const key = env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    console.warn("[sitemap] Backend credentials unavailable — skipping blog URLs.");
    return [];
  }
  const endpoint =
    `${url}/rest/v1/blog_posts` +
    `?select=slug,publish_date,updated_at,created_at&status=eq.published&order=publish_date.desc`;
  try {
    const res = await fetch(endpoint, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
    });
    if (!res.ok) {
      console.warn(`[sitemap] blog_posts request failed (${res.status}) — skipping blog URLs.`);
      return [];
    }
    const rows = await res.json();
    return Array.isArray(rows) ? rows.filter((r) => r && r.slug) : [];
  } catch (err) {
    console.warn("[sitemap] blog_posts request errored — skipping blog URLs.", err?.message || err);
    return [];
  }
}

const escapeXml = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const toDate = (v) => {
  const d = v ? new Date(v) : null;
  return d && !Number.isNaN(d.getTime())
    ? d.toISOString().slice(0, 10)
    : new Date().toISOString().slice(0, 10);
};

async function main() {
  const sourcePath = path.join(ROOT, "public", "sitemap.xml");
  let xml;
  try {
    xml = await fs.readFile(sourcePath, "utf8");
  } catch {
    console.error("[sitemap] public/sitemap.xml not found — nothing to generate.");
    return;
  }

  const env = await loadEnv();
  const posts = await fetchPublishedPosts(env);

  // Drop any previously generated blog block so reruns stay idempotent.
  xml = xml.replace(/\n?\s*<!-- BEGIN blog posts[\s\S]*?<!-- END blog posts -->\n?/g, "\n");

  if (posts.length) {
    const entries = posts
      .map((p) => {
        const loc = `${SITE_ORIGIN}/news/${p.slug}`;
        const lastmod = toDate(p.updated_at || p.publish_date || p.created_at);
        return `  <url>\n    <loc>${escapeXml(loc)}</loc>\n    <lastmod>${lastmod}</lastmod><changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>`;
      })
      .join("\n");
    const block = `\n  <!-- BEGIN blog posts (auto-generated by scripts/gen-sitemap.mjs) -->\n${entries}\n  <!-- END blog posts -->\n`;
    xml = xml.replace("</urlset>", `${block}</urlset>`);
  }

  await fs.mkdir(DIST, { recursive: true });
  await fs.writeFile(path.join(DIST, "sitemap.xml"), xml, "utf8");
  console.log(`[sitemap] Wrote dist/sitemap.xml with ${posts.length} blog post URLs.`);
}

main().catch((err) => {
  console.error("[sitemap] Failed:", err);
  // Never fail the build over the sitemap — dist already has the static copy.
});
