#!/usr/bin/env node
// Post-build sitemap generation.
// Copies public/sitemap.xml (already in dist after vite build) and appends one
// <url> entry per published blog post read from the blog_posts table, so new
// posts are included automatically without hand-editing the sitemap.

import { promises as fs } from "node:fs";
import path from "node:path";
import { SITE_ORIGIN } from "./seo-routes.mjs";
import { ROOT, loadEnv, fetchPublishedPosts as fetchPosts } from "./blog-posts.mjs";

const DIST = path.join(ROOT, "dist");

const fetchPublishedPosts = (env) =>
  fetchPosts(env, "slug,publish_date,updated_at,created_at", "sitemap");

const escapeXml = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const toDate = (v) => {
  const d = v ? new Date(v) : null;
  return d && !Number.isNaN(d.getTime())
    ? d.toISOString().slice(0, 10)
    : new Date().toISOString().slice(0, 10);
};

async function main() {
  const sourcePath = path.join(ROOT, "public", "sitemap.xml");
  let xml;
  try {
    xml = await fs.readFile(sourcePath, "utf8");
  } catch {
    console.error("[sitemap] public/sitemap.xml not found — nothing to generate.");
    return;
  }

  const env = await loadEnv();
  const posts = await fetchPublishedPosts(env);

  // Drop any previously generated blog block so reruns stay idempotent.
  xml = xml.replace(/\n?\s*<!-- BEGIN blog posts[\s\S]*?<!-- END blog posts -->\n?/g, "\n");

  if (posts.length) {
    const entries = posts
      .map((p) => {
        const loc = `${SITE_ORIGIN}/news/${p.slug}`;
        const lastmod = toDate(p.updated_at || p.publish_date || p.created_at);
        return `  <url>\n    <loc>${escapeXml(loc)}</loc>\n    <lastmod>${lastmod}</lastmod><changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>`;
      })
      .join("\n");
    const block = `\n  <!-- BEGIN blog posts (auto-generated by scripts/gen-sitemap.mjs) -->\n${entries}\n  <!-- END blog posts -->\n`;
    xml = xml.replace("</urlset>", `${block}</urlset>`);
  }

  await fs.mkdir(DIST, { recursive: true });
  await fs.writeFile(path.join(DIST, "sitemap.xml"), xml, "utf8");
  console.log(`[sitemap] Wrote dist/sitemap.xml with ${posts.length} blog post URLs.`);
}

main().catch((err) => {
  console.error("[sitemap] Failed:", err);
  // Never fail the build over the sitemap — dist already has the static copy.
});
