// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List Cornerstone Media news/blog posts, newest first, optionally filtered by status.",
  inputSchema: {
    status: z.enum(["draft", "published"]).optional().describe("Filter by post status."),
    search: z.string().trim().min(1).optional().describe("Match text in the post title."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, title, slug, status, excerpt, publish_date, updated_at").order("publish_date", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post with its full content and SEO metadata by slug.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("URL slug of the post, e.g. digital-marketing-birmingham.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No post found with slug "${slug}"` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a new news/blog post. Defaults to draft status so it is not published immediately.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Post title."),
    slug: z3.string().trim().min(1).regex(/^[a-z0-9-]+$/, "Use lowercase letters, numbers and hyphens.").describe("URL slug."),
    content: z3.string().optional().describe("Post body as HTML."),
    excerpt: z3.string().optional().describe("Short summary shown in listings."),
    meta_title: z3.string().optional().describe("SEO title tag."),
    meta_description: z3.string().optional().describe("SEO meta description."),
    status: z3.enum(["draft", "published"]).default("draft").describe("Publication status."),
    publish_date: z3.string().optional().describe("ISO date/time to show as the publish date.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").insert({ ...input, status: input.status ?? "draft", user_id: ctx.getUserId() }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: `Created "${data.title}" (${data.status}) at /news/${data.slug}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var update_blog_post_default = defineTool4({
  name: "update_blog_post",
  title: "Update blog post",
  description: "Update fields of an existing blog post identified by its slug, including publishing a draft.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Slug of the post to update."),
    title: z4.string().trim().min(1).optional(),
    new_slug: z4.string().trim().regex(/^[a-z0-9-]+$/).optional().describe("Change the post slug."),
    content: z4.string().optional().describe("Post body as HTML."),
    excerpt: z4.string().optional(),
    meta_title: z4.string().optional(),
    meta_description: z4.string().optional(),
    status: z4.enum(["draft", "published"]).optional(),
    publish_date: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ slug, new_slug, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = { ...fields };
    if (new_slug) patch.slug = new_slug;
    Object.keys(patch).forEach((k) => patch[k] === void 0 && delete patch[k]);
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").update(patch).eq("slug", slug).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No post updated for slug "${slug}" (not found or not permitted).` }], isError: true };
    return {
      content: [{ type: "text", text: `Updated "${data.title}" (${data.status})` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contact_submissions_default = defineTool5({
  name: "list_contact_submissions",
  title: "List contact enquiries",
  description: "List recent website contact form enquiries (leads), newest first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10).describe("Maximum enquiries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_submissions").select("id, name, email, phone, company, message, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-keyword-rankings.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_keyword_rankings_default = defineTool6({
  name: "list_keyword_rankings",
  title: "List keyword rankings",
  description: "List tracked SEO keywords with their most recent Google Search Console position, clicks and impressions.",
  inputSchema: {
    keyword: z6.string().trim().min(1).optional().describe("Filter to keywords containing this text."),
    limit: z6.number().int().min(1).max(50).default(20).describe("Maximum keywords to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ keyword, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tracked_keywords").select("id, keyword, country, notes, keyword_rankings(position, clicks, impressions, ctr, range_start, range_end, captured_at)").order("keyword", { ascending: true }).limit(limit ?? 20);
    if (keyword) query = query.ilike("keyword", `%${keyword}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((k) => {
      const rankings = [...k.keyword_rankings ?? []].sort(
        (a, b) => new Date(b.range_end).getTime() - new Date(a.range_end).getTime()
      );
      return { id: k.id, keyword: k.keyword, country: k.country, notes: k.notes, latest: rankings[0] ?? null };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { keywords: rows }
    };
  }
});

// src/lib/mcp/tools/add-tracked-keyword.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var add_tracked_keyword_default = defineTool7({
  name: "add_tracked_keyword",
  title: "Add tracked keyword",
  description: "Add a keyword to the SEO rank tracking dashboard.",
  inputSchema: {
    keyword: z7.string().trim().min(1).describe("Search term to track, e.g. 'ppc birmingham'."),
    country: z7.string().trim().min(2).max(3).default("gbr").describe("Country code for the tracking market."),
    notes: z7.string().optional().describe("Optional note about why this keyword matters.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ keyword, country, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tracked_keywords").insert({ keyword, country: country ?? "gbr", notes, created_by: ctx.getUserId() }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: `Now tracking "${data.keyword}" (${data.country})` }],
      structuredContent: { keyword: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kxbnpnejeujlxujuxvtl";
var mcp_default = defineMcp({
  name: "cornerstone-growth-engine",
  title: "Cornerstone Growth Engine",
  version: "0.1.0",
  instructions: "Tools for Cornerstone Media's website: read and write news/blog posts, review contact enquiries, and manage SEO keyword tracking. All tools act as the signed-in Cornerstone Media user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    update_blog_post_default,
    list_contact_submissions_default,
    list_keyword_rankings_default,
    add_tracked_keyword_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
